version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:api_service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/talenvis
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=letmein
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  mysql_db:
      image: "mysql:8.0"
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: talenvis
        MYSQL_USER: talenvis
        MYSQL_PASSWORD: letmein
        MYSQL_ROOT_PASSWORD: root
