server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/talenvis #change this to your database url
    password: letmein #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
